[dracula.hex]
background = "282A36"
current_line = "44475A"
foreground = "F8F8F2"
comment = "6272A4"
selectionForeground = "FFFFFF"
cyan = "8BE9FD"
green = "50FA7B"
orange = "FFB86C"
pink = "FF79C6"
purple = "BD93F9"
red = "FF5555"
yellow = "F1FA8C"
color0 = "21222C"
color9 = "FF6E6E"
color10 = "69FF94"
color11 = "FFFFA5"
color12 = "D6ACFF"
color13 = "FF92DF"
color14 = "A4FFFF"

[bat]
theme = "Dracula"

[shell.env]
editor = "nvim"

[wezterm]
theme = "Dracula (Official)"