#!/usr/bin/env zsh
# Init various programs
eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(zoxide init --cmd cd zsh)"
eval "$(atuin init zsh --disable-up-arrow)"
. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Completions 
# You may also need to forcibly rebuild zcompdump: rm -f ~/.zcompdump; compinit
# If you receive “zsh compinit: insecure directories”. You may need to run this:: chmod -R go-w "$(brew --prefix)/share"
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
FPATH="$HOME/.config/zsh/completions:${FPATH}"
autoload -Uz compinit
compinit

for file in "$HOME"/.config/zsh/*(.)zsh; do 
    . "$file"
done


# Prompt: Place at the end of file
function set_win_title(){
    echo -ne "\033]0; $(basename "$PWD") \007"
}
starship_precmd_user_func="set_win_title"
eval "$(starship init zsh)"